spring.application.name=company-search

spring.datasource.url=jdbc:postgresql://localhost:5433/company_search
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


scraper.base-url=https://find-and-update.company-information.service.gov.uk
scraper.user-agent=CompanySearchService/1.0 (Polixis internship assessment)
scraper.delay-ms=750
scraper.max-companies=100
