spring.application.name=company-search

spring.datasource.url=jdbc:postgresql://localhost:5433/company_search
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false